### ISSUE TITLE
port number error

### ISSUE THREAD

**Issue by furueili** [tolo/HHServices#14]
hi~ In serviceDidResolve delegate method,
I saw the service data as follows
HHService[0x742E3580, MAC000E53290B23, _afpovertcp._tcp, local., MAC000E53290B23.local., (
    "192.168.1.48:88"
), 1] - Resolved last address

and I try to print the port number
NSLog(@"service port number :%i",service.lastResolvedPort);
what I got is 
service port number :22528

please help thx

**Comment by tolo** [comment]
Hi, 

The lastResolvedPort property is an internal property containing a (temporary) port number expressed in network byte order, which is why you get a strange result when you attempt to print it out. 

But I've actually just checked in an update to HHService in which I've added new convenience properties, for instance `resolvedInetAddresses`, which contains a list of resolved addresses on the form IP:PORT.
