### ISSUE TITLE
peer to peer wifi

### ISSUE THREAD

**Issue by geopapyrus** [tolo/HHServices#15]
I can't get the CocoaHTTPServer to work with HHServices over peer to peer wifi. It works just fine via bluetooth.

Did it use to work before via p2p wifi?

Or was it always designed to only work via p2p bluetooth?

Thanks

**Comment by rweichler** [comment]
Only p2p bluetooth or LAN.

**Comment by tolo** [comment]
It's correct that HHServices only supports (or at least was built to support) use via Bluetooth and LAN. This is because it's basically just a higher level layer built upon the multicast DNS (i.e. Bonjour) API, and I suspect peer to peer wifi is implemented as part of another (internal) network infrastructure library. But it might also be possible that multicast DNS API actually support this - I will have to investigate this further. 

However, as of iOS7, NSNetService now actually supports p2p use again, both via bluetooth and wifi, using the [includesPeerToPeer property](https://developer.apple.com/library/prerelease/ios/documentation/Cocoa/Reference/Foundation/Classes/NSNetService_Class/index.html#//apple_ref/occ/instp/NSNetService/includesPeerToPeer). Have a look at the [WiTap demo](https://developer.apple.com/library/ios/samplecode/WiTap/Introduction/Intro.html
) for an example on how to use it. You will find that the HHService API is very similar to the NSNetService API. And since HHServices was created as a workaround for the missing bluetooth p2p support in NSNetService, it does indeed seem that HHServices may now be obsolete for iOS7+ apps :)

But if you don't necessarily need to use CocoaHTTPServer, and if you are only looking for a solution for simple p2p communication between iOS (7+) devices, then it might be worthwhile to have a look at the multipeer framework, as @rweichler suggests.

**Comment by rweichler** [comment]
@tolo Oh wow, I didn't know about that. Yeah, it seems like [Multipeer is a proprietary protocol built on top of P2P Wifi via NSNetService](http://stackoverflow.com/questions/24680709/ios-wifi-direct-communication), it'd be cool if something like dns_sd provides a lower-level API to this stuff

**Comment by xaphod** [comment]
I would definitely NOT say that this framework is deprecated, for iOS 9 and iOS 10. 
If you want to offer P2P bluetooth services without severely degrading wifi performance, then this is the only way. NSNetService degrades wifi, and so does Multipeer. This is because even after you call Multipeer (or the NSNetService equivalent) stopAdvertising, it takes up to 30 seconds for advertising to stop. During advertising, wifi performance is severely degraded. For example on my iPad Air, wifi (infrastructure mode to AP) goes from 2MB/sec to max 150kB/sec. With HHServices however, I can offer full-blown Bluetooth P2P (adhoc) with no wifi interference/degradation at all. For me this is important because I cannot stopAdvertising -- i need peers to be able to join at all times.

@tolo Many, many, many thanks to you for creating this. It has really helped me -- I owe you at least a week of time. I've made you a pull-request for adding the ability to restrict DNS-sd to bluetooth-only, which is what I was after. From the look of apple dev forums, i'm not the only one.

**Comment by tolo** [comment]
Sorry for the late reply here - thanks for your feedback @xaphod and thanks for making me realize this project isn't totally obsolete yet. And really glad to hear it was useful to you! :)

And also, thanks again for the pull-request - stay tuned for version 2.0 of HHServices (checkout the develop branch in the meantime).
